### ISSUE TITLE
Internal server Error when accessing Benchmarks

### ISSUE THREAD

**Issue by eric-warren** [DefectDojo/django-DefectDojo#11973]
**Bug description**
When attempting to go to the view benchmarks page for a product I get a 500 internal server error. This seems to be only for version 2.44.0 as its working fine in 2.43.4. I tested both and new install of 2.44.0 and upgrading from 2.34.4 and both times in 2.44.0 the error occurs

**Steps to reproduce**
1. Go to a product 
2. Try and open either benchmark (ASVS 3 or 4)
3. Then a Internal server error pages shows

**Deployment method** *(select with an `X`)*
- [X] Docker Compose
- [ ] Kubernetes
- [ ] GoDojo

**Environment information**
 - SUSE 15.5
 - Docker Compose 2.14.2 ( I know it an old version but I dont believe it should matter, this is just a test VM I spun up real quick)
 - DefectDojo 2.44.0 

**Logs** 
This seems to be the logs for the error from the UWSGI container

[07/Mar/2025 13:33:15] ERROR [django.request:248] Internal Server Error: /benchmark/1/type/2
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/authorization/authorization_decorators.py", line 36, in _wrapped
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: benchmark_view() got an unexpected keyword argument 'type'
[pid: 31|app: -|req: -/-] 172.25.0.1 (admin) {58 vars in 1240 bytes} [Fri Mar  7 13:33:13 2025] GET /benchmark/1/type/2 => generated 44171 bytes in 1862 msecs (HTTP/1.1 500) 7 headers in 242 bytes (1 switches on core 1)

**Screenshots**

![Image](https://github.com/user-attachments/assets/1df3f89d-187a-4a91-a95c-4116bded6267)

**Comment by valentijnscholten** [comment]
Will be fixed in 2.44.1 on monday.
