### ISSUE TITLE
Error during the installation via AWS ami image

### ISSUE THREAD

**Issue by aliaksxssv** [DefectDojo/django-DefectDojo#9663]
Hey Team,
I use this image https://aws.amazon.com/marketplace/pp/prodview-m2a25gr67xbzk#pdp-reviews

During the installation, I get the next error:
`Setting up Django for DefectDojo...(--------*-)
##############################################################################
  ERROR: 2024/02/29 14:36:26 - Failed to run OS command cd /opt/dojo/django-DefectDojo && source ../bin/activate && python3 [manage.py](http://manage.py/) makemigrations dojo, error was: exit status 1`
  
 In more details it looks like:
 `Traceback (most recent call last):
  File "/opt/dojo/django-DefectDojo/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/dojo/lib/python3.10/site-packages/django/core/management/init.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/dojo/lib/python3.10/site-packages/django/core/management/init.py", line 420, in execute
    django.setup()
  File "/opt/dojo/lib/python3.10/site-packages/django/init.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/dojo/lib/python3.10/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/opt/dojo/lib/python3.10/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.10/importlib/init.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/dojo/django-DefectDojo/dojo/models.py", line 4344, in <module>
    with warnings.catch_warnings(action="ignore", category=ManagerInheritanceWarning):
TypeError: catch_warnings.init() got an unexpected keyword argument 'action'`

**Comment by aliaksxssv** [comment]
I had to pin the 2.31.0 version in the installation settings to bypass the issue.

**Comment by mtesauro** [comment]
@aliaksxssv 
What version was being installed initially before you pinned it at 2.31.0?

**Comment by aliaksxssv** [comment]
By default, it pulls the latest one. In my case, it was 2.31.5.

**Comment by mtesauro** [comment]
> By default, it pulls the latest one. In my case, it was 2.31.5.

OK. Thanks. I knew it pulled the latest but depending on when you ran it and when you posted the PR, the version can't safely be assumed.  I'll test 2.31.5 and see if I can replicate the issue you had.

**Comment by mtesauro** [comment]
@aliaksxssv So, the issue is that Ubuntu 22.04 ships with Python 3.10 and DefectDojo has moved on to Python 3.11.

The failure you saw was caused by a difference between Python 3.10 and 3.11 syntax that was introduced somewhere after 2.31.0. It took a while to figure out where the issue since our containers are using Python 3.11, it only shows up when relying on the OS provided Python. Also the error from Python wasn't particularly helpful:

```
  File "/opt/dojo/django-DefectDojo/dojo/models.py", line 4344, in <module>
    with warnings.catch_warnings(action="ignore", category=ManagerInheritanceWarning):
TypeError: catch_warnings.__init__() got an unexpected keyword argument 'action'
```

If you install on Ubuntu 23.10 which ships with Python 3.11.6, there are no issues. I have tested that successfully. However, the AMI installer has historically stuck with LTS releases for Ubuntu so doesn't support Ubuntu 23.10 in it's current version.

We'll create a new AMI image which works around this issue and I'll drop a note here when that's available.

**Comment by mtesauro** [comment]
@aliaksxssv 
Never got the email from AWS to let me know they approved the updated version of the AMI but I just looked and the updated AMI has been published.

Get the updated one at https://aws.amazon.com/marketplace/pp/prodview-m2a25gr67xbzk that works with versions up to and after 2.31.0
