### ISSUE TITLE
possible Jira regression in 2.31.0: 'JIRA' object has no attribute 'createmeta_issuetypes'

### ISSUE THREAD

**Issue by cedricbu** [DefectDojo/django-DefectDojo#9509]
**Bug description**

After upgrading to 2.31.0, we get this error while linking a product to a Jira instance:

```
[08/Feb/2024 08:25:32] ERROR [dojo.jira_link.helper:1453] 'JIRA' object has no attribute 'createmeta_issuetypes'
Traceback (most recent call last):
  File "/app/dojo/jira_link/helper.py", line 1434, in process_jira_project_form
    if not is_jira_project_valid(jira_project):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/jira_link/helper.py", line 1077, in is_jira_project_valid
    get_issuetype_fields(jira, jira_project.project_key, jira_project.jira_instance.default_issue_type)
  File "/app/dojo/jira_link/helper.py", line 1039, in get_issuetype_fields
    issuetypes = jira.createmeta_issuetypes(project_key)
```

**Steps to reproduce**
1. Create a Jira instance
2. Create a product
3. link that product to the Jira instance

it shows a "JIRA Project config not stored due to errors"  in the WebUI, and the error previously shown appears in the logs.

**Expected behavior**
No error, and successful linking

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [ x] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: debian [from defectdojo docker.io images]
 - DefectDojo version (see footer) or commit message: 3.31.0

**Logs** 
```
[08/Feb/2024 08:25:32] ERROR [dojo.jira_link.helper:1453] 'JIRA' object has no attribute 'createmeta_issuetypes'
Traceback (most recent call last):
  File "/app/dojo/jira_link/helper.py", line 1434, in process_jira_project_form
    if not is_jira_project_valid(jira_project):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/jira_link/helper.py", line 1077, in is_jira_project_valid
    get_issuetype_fields(jira, jira_project.project_key, jira_project.jira_instance.default_issue_type)
  File "/app/dojo/jira_link/helper.py", line 1039, in get_issuetype_fields
    issuetypes = jira.createmeta_issuetypes(project_key)
```

**Additional context** (optional)

Using Jira DataCenter 9.x

My understanding is that this is a regression caused by the Jira library update (from 3.5.2 to 3.6.0), in commit 481c83bb.
The Jira library version 3.6.0 ditched the `JIRA.createmeta_issuetypes()` in the commit [cce214eaf8dd42dc5a5be34b32b95fc29e00de74](https://github.com/pycontribs/jira/commit/cce214eaf8)

**Comment by mtesauro** [comment]
@cedricbu See #9512 - targeting 2.31.1 (Feb 12 2024 release)

**Comment by mtesauro** [comment]
Closing as PR has been merged
