### ISSUE TITLE
Failt to work with sentinel redis 7.0.8

### ISSUE THREAD

**Issue by sebglon** [DefectDojo/django-DefectDojo#8762]
**Bug description**

Deploy the latest version of defectdojoj (2.26.4)
With a redis sentinel v 7.0.8

**Steps to reproduce**
1. Deploy  defectdojo
2. See error on defectdojo-celery-worker
```
[29/Sep/2023 13:15:23] INFO [celery.worker.consumer.connection:22] Connected to sentinel://redis.redis.svc.cluster.local:26379//
[29/Sep/2023 13:15:23] INFO [celery.worker.consumer.mingle:40] mingle: searching for neighbors
[29/Sep/2023 13:15:24] INFO [celery.worker.consumer.mingle:49] mingle: all alone
[29/Sep/2023 13:15:24] INFO [celery.apps.worker:175] celery@defectdojo-celery-worker-87d66745d-nksgk ready.
[29/Sep/2023 13:15:24] CRITICAL [celery.worker:206] Unrecoverable error: TypeError("SentinelManagedConnection.read_response() got an unexpected keyword argument 'push_request'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 340, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 742, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.11/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/usr/local/lib/python3.11/site-packages/kombu/asynchronous/hub.py", line 373, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 1341, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 566, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 910, in _receive
    ret.append(self._receive_one(c))
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 920, in _receive_one
    response = c.parse_response()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 796, in parse_response
    response = self._execute(conn, try_read)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 772, in _execute
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 773, in <lambda>
    lambda: command(*args, **kwargs),
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 794, in try_read
    return conn.read_response(disconnect_on_error=False, push_request=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SentinelManagedConnection.read_response() got an unexpected keyword argument 'push_request'
```

**Expected behavior**
defectdojo-celery-worker is not crashing 

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
 - DefectDojo version: 2.26.4

This ticket seems linked to https://github.com/jazzband/django-redis/issues/678

**Comment by valentijnscholten** [comment]
Is this still happening? I see a lot of upstream updates/changes so this might be resolved.
